all: estacion satelite

estacion : estacion.c
	gcc -Wall -Werror -pedantic -o estacion estacion.c

satelite : satelite.c
	gcc -Wall -Werror -pedantic -o satelite satelite.c

clean :
	rm estacion satelite \
